[versions]
kotlin = "1.9.22"
changelog = "2.2.0"
gradleIntelliJPlugin = "1.16.1"

[plugins.kotlin]
id = "org.jetbrains.kotlin.jvm"
version.ref = "kotlin"

[plugins.gradleIntelliJPlugin]
id = "org.jetbrains.intellij"
version.ref = "gradleIntelliJPlugin"

[plugins.changelog]
id = "org.jetbrains.changelog"
version.ref = "changelog"
